name: lint actions
run-name: Provide ${{ github.sha }} by ${{ github.actor }}
on:
  push:
    branches-ignore:
      - 'main'
      - 'develop'
      - 'release'
    paths:
      - '**.py'
jobs:
  python-linter:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'trend-collector/trendcollector'
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v4
        with:
          python-version: 'pypy3.9'
      - run: pip install -r dev-requirements.txt
#        id: dependencies
      - uses: ricardochaves/python-lint@v1.4.0
        with:
          python-root-list: "trendcollector"
          use-pylint: true
#          extra-pylint-options: "--load-plugins pylint_pydantic"
          use-isort: true
          extra-isort-options: "-r"
