name: lint actions
run-name: Provide ${{ github.sha }} by ${{ github.actor }}
on:
  push:
    branches-ignore:
      - 'main'
      - 'develop'
      - 'release'
    paths:
      - '**.py'
  workflow_dispatch:
jobs:
  python-linter:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './trend-collector'
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          ls
          pwd
      - run: pip install -r dev-requirements.txt
        id: dependencies
      - run: pylint --rcfile ../pylintrc trendcollector
        working-directory: "trend-collector"
      - run: isort trendcollector
